controller_list:
  - name: fake_kuka_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_kuka_hand_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_table_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - tableJoint1
      - tableJoint2
  - name: fake_table_hand_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_combine_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - tableJoint1
      - tableJoint2
initial:  # Define initial robot poses per group
  - group: kuka_arm
    pose: home
  - group: table_arm
    pose: home